name: fivetran_demo
description: ''
version: 0.0.1
author: shubham@cloudaeon.net
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: fivetrandemo
  parentArtefactID: shubhamcloudaeonnetteam
  buildSystem: wheel
  author: null
  createdAt: '2024-04-30 12:52:59'
pipelines:
  pipelines/fivetran_pipeline:
    name: fivetran_pipeline
    description: ''
    author: shubham@cloudaeon.net
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-04-30 12:52:59'
    datasets:
      inputs:
      - datasets/fivetran
      outputs: []
    subgraphs: []
    dependencies: {}
  pipelines/pipe_raw_to_bronze_forecasting:
    name: pipe_raw_to_bronze_forecasting
    description: ''
    author: shubham@cloudaeon.net
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-05-03 09:03:37'
    datasets:
      inputs:
      - datasets/ds_raw_bronze_store
      - datasets/ds_raw_bronze_test
      - datasets/ds_raw_bronze_train
      - datasets/ds_raw_bronze_transactions
      outputs:
      - datasets/ds_rb_dest_data
      - datasets/ds_rb_dest_store
      - datasets/ds_rb_dest_test
      - datasets/ds_rb_dest_transactions
    subgraphs: []
    dependencies: {}
datasets:
  datasets/fivetran:
    name: fivetran
    description: ''
    author: shubham@cloudaeon.net
    createdAt: '2024-04-30 14:10:20'
    mode: batch
    physicalDatasets:
      Fabric_Shubham:
        fabricId: 11913
        datasetType: File
        description: ''
        author: shubham@cloudaeon.net
        createdAt: '2024-04-30 14:10:20'
  datasets/ds_raw_bronze_test:
    name: ds_raw_bronze_test
    description: ''
    author: shubham@cloudaeon.net
    createdAt: '2024-05-03 09:22:58'
    mode: batch
    physicalDatasets:
      Fabric_Shubham:
        fabricId: 11913
        datasetType: File
        description: ''
        author: shubham@cloudaeon.net
        createdAt: '2024-05-03 09:22:58'
  datasets/ds_raw_bronze_store:
    name: ds_raw_bronze_store
    description: ''
    author: shubham@cloudaeon.net
    createdAt: '2024-05-03 09:37:50'
    mode: batch
    physicalDatasets:
      Fabric_Shubham:
        fabricId: 11913
        datasetType: File
        description: ''
        author: shubham@cloudaeon.net
        createdAt: '2024-05-03 09:37:50'
  datasets/ds_raw_bronze_train:
    name: ds_raw_bronze_train
    description: ''
    author: shubham@cloudaeon.net
    createdAt: '2024-05-03 09:39:09'
    mode: batch
    physicalDatasets:
      Fabric_Shubham:
        fabricId: 11913
        datasetType: File
        description: ''
        author: shubham@cloudaeon.net
        createdAt: '2024-05-03 09:39:09'
  datasets/ds_raw_bronze_transactions:
    name: ds_raw_bronze_transactions
    description: ''
    author: shubham@cloudaeon.net
    createdAt: '2024-05-03 09:52:45'
    mode: batch
    physicalDatasets:
      Fabric_Shubham:
        fabricId: 11913
        datasetType: File
        description: ''
        author: shubham@cloudaeon.net
        createdAt: '2024-05-03 09:52:45'
  datasets/ds_rb_dest_test:
    name: ds_rb_dest_test
    description: ''
    author: shubham@cloudaeon.net
    createdAt: '2024-05-03 10:39:00'
    mode: batch
    physicalDatasets:
      Fabric_Shubham:
        fabricId: 11913
        datasetType: File
        description: ''
        author: shubham@cloudaeon.net
        createdAt: '2024-05-03 10:39:00'
  datasets/ds_rb_dest_store:
    name: ds_rb_dest_store
    description: ''
    author: shubham@cloudaeon.net
    createdAt: '2024-05-06 11:21:17'
    mode: batch
    physicalDatasets:
      Fabric_Shubham:
        fabricId: 11913
        datasetType: File
        description: ''
        author: shubham@cloudaeon.net
        createdAt: '2024-05-06 11:21:17'
  datasets/ds_rb_dest_data:
    name: ds_rb_dest_data
    description: ''
    author: shubham@cloudaeon.net
    createdAt: '2024-05-06 11:34:37'
    mode: batch
    physicalDatasets:
      Fabric_Shubham:
        fabricId: 11913
        datasetType: File
        description: ''
        author: shubham@cloudaeon.net
        createdAt: '2024-05-06 11:34:37'
  datasets/ds_rb_dest_transactions:
    name: ds_rb_dest_transactions
    description: ''
    author: shubham@cloudaeon.net
    createdAt: '2024-05-06 11:37:00'
    mode: batch
    physicalDatasets:
      Fabric_Shubham:
        fabricId: 11913
        datasetType: File
        description: ''
        author: shubham@cloudaeon.net
        createdAt: '2024-05-06 11:37:00'
templates: {}
jobs: {}
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-04-30 12:52:59'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- type: plibMaven
  modifiedAt: '2024-04-30T12:55:22.772978Z'
  name: plibMaven
  version: 7.1.93
  id: '868227441'
  createdAt: '2024-04-30T12:55:22.772917Z'
- type: plibPypi
  modifiedAt: '2024-04-30T12:55:22.773033Z'
  name: plibPypi
  version: 1.8.15
  id: '1008357234'
  createdAt: '2024-04-30T12:55:22.77302Z'
projectDependencies:
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.2.10
    isDefault: true
    author: null
    createdAt: '2024-04-30 12:52:35'
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.5
    isDefault: true
    author: null
    createdAt: '2024-04-30 12:52:35'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
