name: fivetran_propecy_transformation
description: ''
version: 0.0.1
author: shubham@cloudaeon.net
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: fivetranpropecytransformation
  parentArtefactID: shubhamcloudaeonnetteam
  buildSystem: wheel
  author: null
  createdAt: '2024-05-09 08:00:39'
pipelines:
  pipelines/pl_forecasting_silver:
    name: pl_forecasting_silver
    description: ''
    author: shubham@cloudaeon.net
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-05-09 08:00:39'
    datasets:
      inputs:
      - datasets/ds_bronze_silver_oil
      - datasets/ds_source_bs_hoilday_ev
      - datasets/ds_source_bs_stores
      - datasets/ds_source_bs_submission
      - datasets/ds_source_bs_test
      - datasets/ds_source_bs_train
      - datasets/ds_source_bs_transactions
      outputs:
      - datasets/ds_target_bs_holiday_ev
      - datasets/ds_target_bs_holiday_stores
      - datasets/ds_target_bs_holiday_test
      - datasets/ds_target_bs_holiday_train
      - datasets/ds_target_bs_holiday_transactions
      - datasets/ds_target_bs_oil
      - datasets/ds_target_bs_submission
    subgraphs: []
    dependencies: {}
  pipelines/pl_forecasting_gold:
    name: pl_forecasting_gold
    description: ''
    author: shubham@cloudaeon.net
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-05-09 08:14:51'
    datasets:
      inputs:
      - datasets/ds_source_sg_holiday_ev
      - datasets/ds_source_sg_oil
      - datasets/ds_source_sg_stores
      - datasets/ds_source_sg_submission
      - datasets/ds_source_sg_test
      - datasets/ds_source_sg_train
      - datasets/ds_source_sg_transactions
      outputs:
      - datasets/ds_target_sg_holiday_ev
      - datasets/ds_target_sg_oil
      - datasets/ds_target_sg_stores
      - datasets/ds_target_sg_submission
      - datasets/ds_target_sg_test
      - datasets/ds_target_sg_train
      - datasets/ds_target_sg_transactions
    subgraphs: []
    dependencies: {}
  pipelines/pl_sap_silver:
    name: pl_sap_silver
    description: ''
    author: shubham@cloudaeon.net
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-05-15 06:48:37'
    datasets:
      inputs:
      - datasets/dss_sap_bs_bseg
      outputs:
      - datasets/dst_sap_bseg
    subgraphs: []
    dependencies: {}
  pipelines/pl_sap_bronze:
    name: pl_sap_bronze
    description: ''
    author: shubham@cloudaeon.net
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-05-15 13:59:27'
    datasets:
      inputs:
      - datasets/dss_sap_bask
      - datasets/dss_sap_bkpf
      - datasets/dss_sap_bs_bseg
      - datasets/dss_sap_csks
      outputs:
      - datasets/dst_sap_bkpf
      - datasets/dst_sap_bseg1
    subgraphs: []
    dependencies: {}
datasets:
  datasets/ds_bronze_silver_oil:
    name: ds_source_bs_oil
    description: ''
    author: shubham@cloudaeon.net
    createdAt: '2024-05-09 08:10:42'
    mode: batch
    physicalDatasets:
      Fabric_Shubham:
        fabricId: 11913
        datasetType: File
        description: ''
        author: shubham@cloudaeon.net
        createdAt: '2024-05-09 08:10:42'
  datasets/ds_target_bs_oil:
    name: ds_target_bs_oil
    description: ''
    author: shubham@cloudaeon.net
    createdAt: '2024-05-09 08:12:49'
    mode: batch
    physicalDatasets:
      Fabric_Shubham:
        fabricId: 11913
        datasetType: File
        description: ''
        author: shubham@cloudaeon.net
        createdAt: '2024-05-09 08:12:49'
  datasets/ds_target_sg_oil:
    name: ds_target_sg_oil
    description: ''
    author: shubham@cloudaeon.net
    createdAt: '2024-05-09 08:17:35'
    mode: batch
    physicalDatasets:
      Fabric_Shubham:
        fabricId: 11913
        datasetType: File
        description: ''
        author: shubham@cloudaeon.net
        createdAt: '2024-05-09 08:17:35'
  datasets/ds_source_sg_oil:
    name: ds_source_sg_oil
    description: ''
    author: shubham@cloudaeon.net
    createdAt: '2024-05-09 10:57:36'
    mode: batch
    physicalDatasets:
      Fabric_Shubham:
        fabricId: 11913
        datasetType: File
        description: ''
        author: shubham@cloudaeon.net
        createdAt: '2024-05-09 10:57:36'
  datasets/ds_source_bs_hoilday_ev:
    name: ds_source_bs_hoilday_ev
    description: ''
    author: shubham@cloudaeon.net
    createdAt: '2024-05-09 11:07:36'
    mode: batch
    physicalDatasets:
      Fabric_Shubham:
        fabricId: 11913
        datasetType: File
        description: ''
        author: shubham@cloudaeon.net
        createdAt: '2024-05-09 11:07:36'
  datasets/ds_source_bs_submission:
    name: ds_source_bs_submission
    description: ''
    author: shubham@cloudaeon.net
    createdAt: '2024-05-09 11:09:18'
    mode: batch
    physicalDatasets:
      Fabric_Shubham:
        fabricId: 11913
        datasetType: File
        description: ''
        author: shubham@cloudaeon.net
        createdAt: '2024-05-09 11:09:18'
  datasets/ds_source_bs_stores:
    name: ds_source_bs_stores
    description: ''
    author: shubham@cloudaeon.net
    createdAt: '2024-05-09 11:10:10'
    mode: batch
    physicalDatasets:
      Fabric_Shubham:
        fabricId: 11913
        datasetType: File
        description: ''
        author: shubham@cloudaeon.net
        createdAt: '2024-05-09 11:10:10'
  datasets/ds_target_bs_holiday_ev:
    name: ds_target_bs_holiday_ev
    description: ''
    author: shubham@cloudaeon.net
    createdAt: '2024-05-09 11:12:40'
    mode: batch
    physicalDatasets:
      Fabric_Shubham:
        fabricId: 11913
        datasetType: File
        description: ''
        author: shubham@cloudaeon.net
        createdAt: '2024-05-09 11:12:40'
  datasets/ds_source_bs_test:
    name: ds_source_bs_test
    description: ''
    author: shubham@cloudaeon.net
    createdAt: '2024-05-10 07:06:15'
    mode: batch
    physicalDatasets:
      Fabric_Shubham:
        fabricId: 11913
        datasetType: File
        description: ''
        author: shubham@cloudaeon.net
        createdAt: '2024-05-10 07:06:15'
  datasets/ds_source_bs_train:
    name: ds_source_bs_train
    description: ''
    author: shubham@cloudaeon.net
    createdAt: '2024-05-10 07:07:12'
    mode: batch
    physicalDatasets:
      Fabric_Shubham:
        fabricId: 11913
        datasetType: File
        description: ''
        author: shubham@cloudaeon.net
        createdAt: '2024-05-10 07:07:12'
  datasets/ds_source_bs_transactions:
    name: ds_source_bs_transactions
    description: ''
    author: shubham@cloudaeon.net
    createdAt: '2024-05-10 07:08:07'
    mode: batch
    physicalDatasets:
      Fabric_Shubham:
        fabricId: 11913
        datasetType: File
        description: ''
        author: shubham@cloudaeon.net
        createdAt: '2024-05-10 07:08:07'
  datasets/ds_target_bs_submission:
    name: ds_target_bs_submission
    description: ''
    author: shubham@cloudaeon.net
    createdAt: '2024-05-10 07:09:35'
    mode: batch
    physicalDatasets:
      Fabric_Shubham:
        fabricId: 11913
        datasetType: File
        description: ''
        author: shubham@cloudaeon.net
        createdAt: '2024-05-10 07:09:35'
  datasets/ds_target_bs_holiday_stores:
    name: ds_target_bs_stores
    description: ''
    author: shubham@cloudaeon.net
    createdAt: '2024-05-10 07:12:05'
    mode: batch
    physicalDatasets:
      Fabric_Shubham:
        fabricId: 11913
        datasetType: File
        description: ''
        author: shubham@cloudaeon.net
        createdAt: '2024-05-10 07:12:05'
  datasets/ds_target_bs_holiday_test:
    name: ds_target_bs_holiday_test
    description: ''
    author: shubham@cloudaeon.net
    createdAt: '2024-05-10 07:14:54'
    mode: batch
    physicalDatasets:
      Fabric_Shubham:
        fabricId: 11913
        datasetType: File
        description: ''
        author: shubham@cloudaeon.net
        createdAt: '2024-05-10 07:14:54'
  datasets/ds_target_bs_holiday_train:
    name: ds_target_bs_holiday_train
    description: ''
    author: shubham@cloudaeon.net
    createdAt: '2024-05-10 07:15:32'
    mode: batch
    physicalDatasets:
      Fabric_Shubham:
        fabricId: 11913
        datasetType: File
        description: ''
        author: shubham@cloudaeon.net
        createdAt: '2024-05-10 07:15:32'
  datasets/ds_target_bs_holiday_transactions:
    name: ds_target_bs_transactions
    description: ''
    author: shubham@cloudaeon.net
    createdAt: '2024-05-10 07:16:25'
    mode: batch
    physicalDatasets:
      Fabric_Shubham:
        fabricId: 11913
        datasetType: File
        description: ''
        author: shubham@cloudaeon.net
        createdAt: '2024-05-10 07:16:25'
  datasets/ds_source_sg_holiday_ev:
    name: ds_source_sg_holiday_ev
    description: ''
    author: shubham@cloudaeon.net
    createdAt: '2024-05-10 07:29:38'
    mode: batch
    physicalDatasets:
      Fabric_Shubham:
        fabricId: 11913
        datasetType: File
        description: ''
        author: shubham@cloudaeon.net
        createdAt: '2024-05-10 07:29:38'
  datasets/ds_source_sg_submission:
    name: ds_source_sg_submission
    description: ''
    author: shubham@cloudaeon.net
    createdAt: '2024-05-10 07:30:39'
    mode: batch
    physicalDatasets:
      Fabric_Shubham:
        fabricId: 11913
        datasetType: File
        description: ''
        author: shubham@cloudaeon.net
        createdAt: '2024-05-10 07:30:39'
  datasets/ds_source_sg_stores:
    name: ds_source_sg_stores
    description: ''
    author: shubham@cloudaeon.net
    createdAt: '2024-05-10 07:56:26'
    mode: batch
    physicalDatasets:
      Fabric_Shubham:
        fabricId: 11913
        datasetType: File
        description: ''
        author: shubham@cloudaeon.net
        createdAt: '2024-05-10 07:56:26'
  datasets/ds_source_sg_test:
    name: ds_source_sg_test
    description: ''
    author: shubham@cloudaeon.net
    createdAt: '2024-05-10 07:57:11'
    mode: batch
    physicalDatasets:
      Fabric_Shubham:
        fabricId: 11913
        datasetType: File
        description: ''
        author: shubham@cloudaeon.net
        createdAt: '2024-05-10 07:57:11'
  datasets/ds_source_sg_train:
    name: ds_source_sg_train
    description: ''
    author: shubham@cloudaeon.net
    createdAt: '2024-05-10 07:58:03'
    mode: batch
    physicalDatasets:
      Fabric_Shubham:
        fabricId: 11913
        datasetType: File
        description: ''
        author: shubham@cloudaeon.net
        createdAt: '2024-05-10 07:58:03'
  datasets/ds_source_sg_transactions:
    name: ds_source_sg_transactions
    description: ''
    author: shubham@cloudaeon.net
    createdAt: '2024-05-10 07:59:29'
    mode: batch
    physicalDatasets:
      Fabric_Shubham:
        fabricId: 11913
        datasetType: File
        description: ''
        author: shubham@cloudaeon.net
        createdAt: '2024-05-10 07:59:29'
  datasets/ds_target_sg_holiday_ev:
    name: ds_target_sg_holiday_ev
    description: ''
    author: shubham@cloudaeon.net
    createdAt: '2024-05-10 08:02:57'
    mode: batch
    physicalDatasets:
      Fabric_Shubham:
        fabricId: 11913
        datasetType: File
        description: ''
        author: shubham@cloudaeon.net
        createdAt: '2024-05-10 08:02:57'
  datasets/ds_target_sg_submission:
    name: ds_target_sg_submission
    description: ''
    author: shubham@cloudaeon.net
    createdAt: '2024-05-10 08:04:59'
    mode: batch
    physicalDatasets:
      Fabric_Shubham:
        fabricId: 11913
        datasetType: File
        description: ''
        author: shubham@cloudaeon.net
        createdAt: '2024-05-10 08:04:59'
  datasets/ds_target_sg_stores:
    name: ds_target_sg_stores
    description: ''
    author: shubham@cloudaeon.net
    createdAt: '2024-05-10 08:07:09'
    mode: batch
    physicalDatasets:
      Fabric_Shubham:
        fabricId: 11913
        datasetType: File
        description: ''
        author: shubham@cloudaeon.net
        createdAt: '2024-05-10 08:07:09'
  datasets/ds_target_sg_test:
    name: ds_target_sg_test
    description: ''
    author: shubham@cloudaeon.net
    createdAt: '2024-05-10 08:08:01'
    mode: batch
    physicalDatasets:
      Fabric_Shubham:
        fabricId: 11913
        datasetType: File
        description: ''
        author: shubham@cloudaeon.net
        createdAt: '2024-05-10 08:08:01'
  datasets/ds_target_sg_train:
    name: ds_target_sg_train
    description: ''
    author: shubham@cloudaeon.net
    createdAt: '2024-05-10 08:10:06'
    mode: batch
    physicalDatasets:
      Fabric_Shubham:
        fabricId: 11913
        datasetType: File
        description: ''
        author: shubham@cloudaeon.net
        createdAt: '2024-05-10 08:10:06'
  datasets/ds_target_sg_transactions:
    name: ds_target_sg_transactions
    description: ''
    author: shubham@cloudaeon.net
    createdAt: '2024-05-10 08:11:28'
    mode: batch
    physicalDatasets:
      Fabric_Shubham:
        fabricId: 11913
        datasetType: File
        description: ''
        author: shubham@cloudaeon.net
        createdAt: '2024-05-10 08:11:28'
  datasets/dss_sap_bs:
    name: dss_sap_bs
    description: ''
    author: shubham@cloudaeon.net
    createdAt: '2024-05-15 06:56:37'
    mode: batch
    physicalDatasets:
      Fabric_Shubham:
        fabricId: 11913
        datasetType: File
        description: ''
        author: shubham@cloudaeon.net
        createdAt: '2024-05-15 06:56:37'
  datasets/dss_sap_rseg:
    name: dss_sap_rseg
    description: ''
    author: shubham@cloudaeon.net
    createdAt: '2024-05-15 08:16:01'
    mode: batch
    physicalDatasets:
      Fabric_Shubham:
        fabricId: 11913
        datasetType: File
        description: ''
        author: shubham@cloudaeon.net
        createdAt: '2024-05-15 08:16:01'
  datasets/dss_sap_bs_bseg:
    name: dss_sap_bs_bseg
    description: ''
    author: shubham@cloudaeon.net
    createdAt: '2024-05-15 10:45:45'
    mode: batch
    physicalDatasets:
      Fabric_Shubham:
        fabricId: 11913
        datasetType: File
        description: ''
        author: shubham@cloudaeon.net
        createdAt: '2024-05-15 10:45:45'
  datasets/test:
    name: test
    description: ''
    author: shubham@cloudaeon.net
    createdAt: '2024-05-15 12:48:12'
    mode: batch
    physicalDatasets:
      Fabric_Shubham:
        fabricId: 11913
        datasetType: Database
        description: ''
        author: shubham@cloudaeon.net
        createdAt: '2024-05-15 12:48:12'
  datasets/dst_sap_bseg:
    name: dst_sap_bseg
    description: ''
    author: shubham@cloudaeon.net
    createdAt: '2024-05-15 13:46:07'
    mode: batch
    physicalDatasets:
      Fabric_Shubham:
        fabricId: 11913
        datasetType: File
        description: ''
        author: shubham@cloudaeon.net
        createdAt: '2024-05-15 13:46:07'
  datasets/dst_sap_bseg1:
    name: dst_sap_bseg1
    description: ''
    author: shubham@cloudaeon.net
    createdAt: '2024-05-15 14:07:36'
    mode: batch
    physicalDatasets:
      Fabric_Shubham:
        fabricId: 11913
        datasetType: File
        description: ''
        author: shubham@cloudaeon.net
        createdAt: '2024-05-15 14:07:36'
  datasets/dss_sap_bkpf:
    name: dss_sap_bkpf
    description: ''
    author: shubham@cloudaeon.net
    createdAt: '2024-05-15 14:21:22'
    mode: batch
    physicalDatasets:
      Fabric_Shubham:
        fabricId: 11913
        datasetType: File
        description: ''
        author: shubham@cloudaeon.net
        createdAt: '2024-05-15 14:21:22'
  datasets/dss_sap_bask:
    name: dss_sap_bask
    description: ''
    author: shubham@cloudaeon.net
    createdAt: '2024-05-15 14:28:30'
    mode: batch
    physicalDatasets:
      Fabric_Shubham:
        fabricId: 11913
        datasetType: File
        description: ''
        author: shubham@cloudaeon.net
        createdAt: '2024-05-15 14:28:30'
  datasets/dst_sap_bkpf:
    name: dst_sap_bkpf
    description: ''
    author: shubham@cloudaeon.net
    createdAt: '2024-05-16 06:53:44'
    mode: batch
    physicalDatasets:
      Fabric_Shubham:
        fabricId: 11913
        datasetType: Database
        description: ''
        author: shubham@cloudaeon.net
        createdAt: '2024-05-16 06:53:44'
  datasets/dss_sap_csks:
    name: dss_sap_csks
    description: ''
    author: shubham@cloudaeon.net
    createdAt: '2024-05-16 07:19:13'
    mode: batch
    physicalDatasets:
      Fabric_Shubham:
        fabricId: 11913
        datasetType: File
        description: ''
        author: shubham@cloudaeon.net
        createdAt: '2024-05-16 07:19:13'
templates: {}
jobs: {}
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-05-09 08:00:39'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- type: plibMaven
  modifiedAt: '2024-05-15T14:00:03.199559Z'
  name: plibMaven
  version: 7.1.95
  id: '562997867'
  createdAt: '2024-05-15T14:00:03.199448Z'
- type: plibPypi
  modifiedAt: '2024-05-15T14:00:03.199677Z'
  name: plibPypi
  version: 1.8.15
  id: '2055311183'
  createdAt: '2024-05-15T14:00:03.199646Z'
projectDependencies:
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.2.12
    isDefault: true
    author: null
    createdAt: '2024-05-09 07:59:28'
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.5
    isDefault: true
    author: null
    createdAt: '2024-05-09 07:59:28'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
